Repository falcosecurity/falcosidekick, pull requests merged in 2019-10, with the labels that each got.

#38 Don't produce duplicate entries when events have non-string fields
  outputs/alertmanager.go
  outputs/client_test.go
  outputs/slack.go
  outputs/teams.go
Labels: bug

#39 add new output : Opsgenie + new avatar
  CHANGELOG.md
  README.md
  config.go
  config_example.yaml
  deploy/helm/falcosidekick/Chart.yaml
  deploy/helm/falcosidekick/templates/deployment.yaml
  deploy/helm/falcosidekick/templates/secrets.yaml
  deploy/helm/falcosidekick/values.yaml
  handlers.go
  imgs/falcosidekick_color.png
  imgs/falcosidekick_color.svg
  imgs/opsgenie.png
  main.go
  outputs/alertmanager_test.go
  outputs/client.go
  outputs/client_test.go
  outputs/datadog.go
  outputs/datadog_test.go
  outputs/influxdb.go
  outputs/influxdb_test.go
  outputs/loki.go
  outputs/loki_test.go
  outputs/opsgenie.go
  outputs/opsgenie_test.go
  outputs/slack.go
  outputs/slack_test.go
  outputs/teams_test.go
  stats.go
  types/types.go
Labels: enhancement, new feature

#40 Add format string for Slack outputs
  README.md
  config.go
  config_example.yaml
  deploy/helm/falcosidekick/templates/deployment.yaml
  deploy/helm/falcosidekick/values.yaml
  outputs/slack.go
  outputs/slack_test.go
  types/types.go
Labels: enhancement

#41 Fix Helm Template Error
  deploy/helm/falcosidekick/templates/deployment.yaml
Labels: bug

#42 docs: fix typo in readme
  README.md
Labels: bug
