Repository falcosecurity/falcosidekick, pull requests merged in 2020-10, with the labels that each got.

#85 falco helm Chart variables have moved from underscores to CamelCase
  README.md
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, size/S

#86 docs: clarify installation instructions
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#90 update(OWNERS): adding myself to approvers
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#91 release 2.15.0
  CHANGELOG.md
  README.md
  deploy/helm/falcosidekick/.helmignore
  deploy/helm/falcosidekick/Chart.yaml
  deploy/helm/falcosidekick/templates/NOTES.txt
  deploy/helm/falcosidekick/templates/_helpers.tpl
  deploy/helm/falcosidekick/templates/aadpodidentity.yaml
  deploy/helm/falcosidekick/templates/clusterrole.yaml
  deploy/helm/falcosidekick/templates/clusterrolebinding.yaml
  deploy/helm/falcosidekick/templates/deployment.yaml
  deploy/helm/falcosidekick/templates/ingress.yaml
  deploy/helm/falcosidekick/templates/rbac.yaml
  deploy/helm/falcosidekick/templates/secrets.yaml
  deploy/helm/falcosidekick/templates/service.yaml
  deploy/helm/falcosidekick/templates/tests/test-connection.yaml
  deploy/helm/falcosidekick/values.yaml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#94 prepare 2.16.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS
