Repository falcosecurity/falcosidekick, pull requests merged in 2020-11, with the labels that each got.

#95 fix: update falcosidekick deployment instructions
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#98 update changelog for 2.17.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#101 build(.circleci): correct tags filter
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#103 dependecies: update several deps
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XL

#105 add circleci badge
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#110 Refactor type assertion in output
  outputs/alertmanager.go
  outputs/aws.go
  outputs/datadog.go
  outputs/discord.go
  outputs/influxdb.go
  outputs/loki.go
  outputs/mattermost.go
  outputs/opsgenie.go
  outputs/rocketchat.go
  outputs/slack.go
  outputs/teams.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#106 clean a bit the circleci config
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#111 Fix wrong output figure for Google Chat
  README.md
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#112 update test to use testify
  outputs/googlechat_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#113 Add Rocketchat output test
  outputs/rocketchat_test.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#114 update changelog for 2.18.0
  CHANGELOG.md
  README.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#116 Refactor HTTP server handler
  handlers.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/S

#118 Fix Discord output's Prometheus metrics
  outputs/discord.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#119 Fix README.md's quick test example
  README.md
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#121 Chore: Fix small typo "Acces"
  outputs/client.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#122 fix discord image link
  README.md
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#125 Fix typo Rockatchat to Rocketchat
  README.md
  config_example.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#126 Add .dockerignore for small Docker images
  .dockerignore
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#123 add initial contributing document
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#128 Bump go version to 1.15
  .circleci/config.yml
  go.mod
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#127 Add Cloudwatch Logs Output
  README.md
  config.go
  config_example.yaml
  handlers.go
  main.go
  outputs/aws.go
  stats.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#129 Add missing AWS Cloud Watch Logs minimum priority description in README.md
  README.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#130 fix nil pointer when gcp config is incorrect + normalize labels of stats
  handlers.go
  main.go
  outputs/constants.go
  stats.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M
