Repository falcosecurity/falcosidekick, pull requests merged in 2020-07, with the labels that each got.

#65 new: PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, kind/documentation

#64 docs: OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note, size/XS

#68 fix wrong port in notes for helm chart + add details for enabling eve…
  README.md
  config_example.yaml
  deploy/helm/falcosidekick/Chart.yaml
  deploy/helm/falcosidekick/templates/NOTES.txt
  deploy/helm/falcosidekick/values.yaml
  example.yaml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#69 update(.github): remove release-note block from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, size/S
