Repository falcosecurity/falcosidekick, pull requests merged in 2020-09, with the labels that each got.

#78 fix, unsupported strings in alertmanager keys
  outputs/alertmanager.go
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#79 cardinality matters, n_events labels on alertmanager
  outputs/alertmanager.go
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/M

#82 Repair alertmanager
  outputs/alertmanager.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S
