Repository falcosecurity/falcosidekick, pull requests merged in 2020-01, with the labels that each got.

#54 add Pod Secuity Policy to helm chart
  deploy/helm/falcosidekick/Chart.yaml
  deploy/helm/falcosidekick/templates/clusterrole.yaml
  deploy/helm/falcosidekick/templates/clusterrolebinding.yaml
  deploy/helm/falcosidekick/values.yaml
Labels: enhancement, new feature

#53 Use numerical USER to allow usage with k8s Pod Security Policies
  Dockerfile
Labels: enhancement

#56 updated typo in smtp logs.
  outputs/smtp.go
Labels: bug
