Repository falcosecurity/falcosidekick, pull requests merged in 2020-12, with the labels that each got.

#131 prepare changelog for 2.19.0
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#136 ci: when merging to the main branch push the latest tag image to dockerhub
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#135 output: add nats streaming stan output
  README.md
  config.go
  go.mod
  go.sum
  handlers.go
  main.go
  outputs/constants.go
  outputs/stan.go
  stats.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#141 fix(nats): NATS values were not initialized in viper
  config.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#138 ci: clean filters to avoid confusion
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#139 kafka: refactor kafka to use another library
  Dockerfile
  Makefile
  README.md
  config_example.yaml
  go.mod
  go.sum
  handlers.go
  main.go
  outputs/client.go
  outputs/kafka.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#143 readme: update development part
  Makefile
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#145 alertmanager: add missing statds/dogstastd metrics
  outputs/alertmanager.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#147 datadog: add missing statds/dogstastd metrics
  outputs/datadog.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#148 discord: add missing statds/dogstastd metrics
  outputs/discord.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#149 elasticsearch: add missing statds/dogstastd metrics
  outputs/elasticsearch.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#150 googlechat: add missing statds/dogstastd metrics
  outputs/googlechat.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#160 docs(.github): removing "helm" area label
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#159 nats: organize the nats code to be similar to others
  outputs/nats.go
  outputs/stan.go
Labels: approved, area/outputs, dco-signoff: yes, kind/cleanup, lgtm, size/M

#146 azure: add missing statds/dogstastd metrics
  outputs/azure.go
Labels: approved, area/outputs, dco-signoff: yes, kind/cleanup, lgtm, size/M

#151 influxdb: add missing statds/dogstastd metrics
  outputs/influxdb.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#154 opsgenie: add missing statds/dogstastd metrics
  outputs/opsgenie.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#152 loki: add missing statds/dogstastd metrics
  outputs/loki.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#156 slack: add missing statds/dogstastd metrics
  outputs/slack.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#157 teams: add missing statds/dogstastd metrics
  outputs/teams.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#158 webhook: add missing statds/dogstastd metrics
  outputs/webhook.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#162 add cpanato as official maintainer
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#153 mattermost: add missing statds/dogstastd metrics
  outputs/mattermost.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#155 rocketchat: add missing statds/dogstastd metrics
  outputs/rocketchat.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#166 Add KeisukeYamashita as maintainer
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS
