Repository falcosecurity/falcosidekick, pull requests merged in 2020-08, with the labels that each got.

#61 Discord output
  .gitignore
  README.md
  config.go
  config_example.yaml
  handlers.go
  imgs/discord.png
  main.go
  outputs/discord.go
  stats.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#72 Username parameter for slack/mattermost/rocketchat
  README.md
  config.go
  config_example.yaml
  go.mod
  imgs/falco_with_falcosidekick.png
  outputs/slack.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/documentation, kind/feature, lgtm, size/M

#73 add nibalizer as approver/reviewer
  OWNERS
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/XS

#75 prepare 2.14.0
  CHANGELOG.md
  Dockerfile
  README.md
  config_example.yaml
  deploy/helm/falcosidekick/Chart.yaml
  deploy/helm/falcosidekick/templates/deployment.yaml
  deploy/helm/falcosidekick/templates/secrets.yaml
  deploy/helm/falcosidekick/values.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M
