Repository falcosecurity/falcosidekick, pull requests merged in 2021-04, with the labels that each got.

#215 prepare changelog for 2.22.0
  CHANGELOG.md
Labels: approved, area/build, dco-signoff: yes, kind/feature, lgtm, size/S

#217 circleci: run workflow when creating tags
  .circleci/config.yml
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, size/S

#218 fix changelog for last 2 releases
  CHANGELOG.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#226 re-order fields for slack/rocket/mattermost + sort them alphabetically
  go.mod
  outputs/googlechat.go
  outputs/mattermost.go
  outputs/mattermost_test.go
  outputs/rocketchat.go
  outputs/rocketchat_test.go
  outputs/slack.go
  outputs/slack_test.go
  outputs/utils.go
Labels: approved, area/outputs, dco-signoff: yes, kind/feature, lgtm, size/L

#227 fix statsd/dogstatsd: NewStatsdClient never initiated for Dogstatsd
  main.go
  outputs/statsd.go
Labels: approved, area/outputs, dco-signoff: yes, kind/bug, lgtm, size/M

#228 fix duplicated log messages and some format of log prefix
  outputs/alertmanager.go
  outputs/azure.go
  outputs/cloudevents.go
  outputs/datadog.go
  outputs/discord.go
  outputs/elasticsearch.go
  outputs/googlechat.go
  outputs/influxdb.go
  outputs/loki.go
  outputs/mattermost.go
  outputs/opsgenie.go
  outputs/pagerduty.go
  outputs/rocketchat.go
  outputs/slack.go
  outputs/stan.go
  outputs/teams.go
  outputs/webhook.go
  outputs/webui.go
Labels: approved, area/outputs, dco-signoff: yes, kind/bug, lgtm, size/S

#232 set default values for openfaas parameters
  README.md
  config_example.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/M

#233 add rabbitmq in list of available outputs
  README.md
Labels: approved, area/outputs, dco-signoff: yes, kind/documentation, lgtm, size/XS

#229 Adds initial support to sending metric alert to wavefront
  README.md
  config.go
  config_example.yaml
  go.mod
  go.sum
  handlers.go
  main.go
  outputs/client.go
  outputs/wavefront.go
  stats.go
  types/types.go
Labels: approved, area/outputs, dco-signoff: yes, kind/feature, lgtm, size/L

#236 docs(README.md): correct link
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS
