Repository falcosecurity/falcosidekick, pull requests merged in 2021-02, with the labels that each got.

#179 resolve gosec issues or add nosec annotations
  config.go
  handlers.go
  outputs/aws.go
  outputs/client.go
  outputs/kafka.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#184 fix missing space in webui log
  outputs/webui.go
Labels: approved, area/outputs, dco-signoff: yes, kind/bug, lgtm, size/XS

#185 set Webui.URL default address empty
  config.go
Labels: approved, area/config, dco-signoff: yes, kind/bug, lgtm, size/XS

#187 Add listenaddress option
  README.md
  config.go
  config_example.yaml
  main.go
  outputs/webui.go
  types/types.go
Labels: approved, area/config, dco-signoff: yes, kind/cleanup, kind/feature, lgtm, size/S

#189 prepare 2.21.0
  CHANGELOG.md
Labels: approved, area/build, dco-signoff: yes, kind/feature, lgtm, size/S

#192 Upgrade to Go 1.16
  .circleci/config.yml
  go.mod
  go.sum
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, size/L

#193 Upgrade Go in Dockerfile and use smaller build image
  Dockerfile
Labels: approved, area/build, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#194 Fix: use HostPort insted of URL
  config.go
Labels: approved, area/outputs, dco-signoff: yes, kind/bug, lgtm, size/XS
