Repository falcosecurity/falcosidekick, pull requests merged in 2021-08, with the labels that each got.

#263 Add KafkaRest as new output for Falco Sidekick
  README.md
  config.go
  config_example.yaml
  go.mod
  go.sum
  handlers.go
  main.go
  outputs/kafkarest.go
  stats.go
  types/types.go
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/L, area/outputs

#265 ci: add step to push to aws ecr too
  .circleci/config.yml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/M, area/build

#267 ci: include required deps for build and push to ecr
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, area/build

#268 ci: include required deps for build and push to ecr
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/S, area/build

#269 ci: add missing bash dep on push to ecr job
  .circleci/config.yml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, area/build

#266 prepare v2.24.0
  CHANGELOG.md
  README.md
  go.sum
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/M, area/build, area/outputs
