Repository falcosecurity/falcosidekick, pull requests merged in 2021-06, with the labels that each got.

#244 Fixed markdown typo in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#250 prepare changelog for 2.23.0 + split outputs in readme in different s…
  CHANGELOG.md
  README.md
Labels: approved, area/build, area/outputs, dco-signoff: yes, kind/feature, lgtm, size/L

#251 add missing GCP functions in changelog of 2.23.0
  CHANGELOG.md
  README.md
Labels: approved, area/outputs, dco-signoff: yes, kind/documentation, lgtm, size/XS

#249 Nats only needs one YAML block.
  config_example.yaml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#246 Add DCO explanation.
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#253 prepare 2.23.1
  CHANGELOG.md
Labels: approved, area/build, dco-signoff: yes, kind/bug, lgtm, size/XS
