Repository falcosecurity/falcosidekick, pull requests merged in 2021-05, with the labels that each got.

#237 proposing myself as an approver and a reviewer to the project
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, needs-kind, size/XS

#238 AWS IRSA support
  outputs/aws.go
Labels: approved, area/outputs, dco-signoff: yes, kind/bug, lgtm, size/XS

#242 check nil pointer before reference to SSECustomerKeyMD5
  outputs/aws.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#241 add Google Cloud Functions output type
  README.md
  config.go
  go.mod
  go.sum
  handlers.go
  main.go
  outputs/client.go
  outputs/gcp.go
  stats.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#243 add Google Cloud Run output type
  README.md
  config.go
  config_example.yaml
  handlers.go
  main.go
  outputs/client.go
  outputs/gcpcloudrun.go
  stats.go
  types/types.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M
