Repository falcosecurity/falcosidekick, pull requests merged in 2021-12, with the labels that each got.

#290 add version to falcosidekick
  .circleci/config.yml
  .goreleaser.yml
  Makefile
  config.go
  main.go
  version.go
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/L, area/outputs

#291 update base image to alpine 3.15
  Dockerfile
Labels: kind/cleanup, kind/feature, dco-signoff: yes, size/XS, approved, lgtm, area/build

#289 upgrade golangci-lint to 1.43.0
  Makefile
Labels: kind/cleanup, dco-signoff: yes, size/XS, approved, lgtm, area/build

#292 update Golang to 1.17.4
  .circleci/config.yml
  go.mod
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/L, area/build

#293 ci: set the no outpout timeout for the circleci jobs
  .circleci/config.yml
Labels: kind/cleanup, dco-signoff: yes, size/XS, approved, lgtm, area/build

#294 ci: fix ci to use make to inject some variables
  .circleci/config.yml
Labels: kind/bug, kind/cleanup, dco-signoff: yes, size/XS, approved, lgtm, area/build

#295 Adds support for AWS clients to use EKS OIDC web identity tokens when running in a cluster with IRSA
  outputs/aws.go
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/M, area/outputs
