Repository falcosecurity/falcosidekick, pull requests merged in 2023-01, with the labels that each got.

#387 AWS Security Lake output
  README.md
  config.go
  config_example.yaml
  go.mod
  go.sum
  handlers.go
  main.go
  outputs/aws.go
  outputs/awssecuritylake.go
  outputs/webui.go
  stats.go
  types/types.go
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/XL, area/outputs

#388 update changelog for 2.27.0
  CHANGELOG.md
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/M, area/build, area/config, area/outputs

#391 update cosign keys
  release/cosign.key
  release/cosign.pub
Labels: kind/cleanup, dco-signoff: yes, approved, lgtm, size/S, area/build
