Repository falcosecurity/falcosidekick, pull requests merged in 2023-10, with the labels that each got.

#666 Bug: mTLS client verification fails due to missing ClientCAs configuration in server side
  main.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, needs-kind, area/config

#668 update logs for TLS
  README.md
  config_example.yaml
  main.go
Labels: kind/cleanup, dco-signoff: yes, approved, lgtm, size/S, area/config

#682 fix wrong env var for pagerduty output
  docs/outputs/pagerduty.md
Labels: dco-signoff: yes, size/XS, approved, lgtm, needs-kind
