Repository falcosecurity/falcosidekick, pull requests merged in 2023-03, with the labels that each got.

#396 Add Redis output
  README.md
  config.go
  config_example.yaml
  go.mod
  go.sum
  handlers.go
  main.go
  outputs/client.go
  outputs/redis.go
  stats.go
  types/types.go
Labels: dco-signoff: yes, approved, lgtm, size/L, needs-kind, area/outputs

#410 add option to trigger manually and update docker secret name
  .github/workflows/push-main.yml
Labels: kind/cleanup, dco-signoff: yes, size/XS, approved, lgtm, area/build

#418 update versions of all modules (except wavefront)
  go.mod
  go.sum
Labels: kind/cleanup, dco-signoff: yes, approved, lgtm, size/XXL, area/build

#419 remove brackets in labels + add Number as DataType
  outputs/aws.go
Labels: kind/bug, kind/feature, dco-signoff: yes, approved, lgtm, size/S, area/outputs

#420 feat(prometheus-hostname): adding hostname from playload as label of prom events metric
  handlers.go
Labels: kind/feature, dco-signoff: yes, size/XS, approved, lgtm, area/outputs

#426 fix: timescaledb hypertablename config
  config.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, area/outputs

#421 add bracketreplacer setting
  README.md
  config.go
  config_example.yaml
  handlers.go
  types/types.go
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/M, area/outputs

#428 allow to set custom headers for loki, elasticsearch and grafana
  README.md
  config.go
  config_example.yaml
  outputs/elasticsearch.go
  outputs/grafana.go
  outputs/loki.go
  types/types.go
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/M, area/outputs

#429 fix panic with assertion when the value of the output fields are nil …
  handlers.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/S, area/outputs
