Repository falcosecurity/falcosidekick, pull requests merged in 2023-09, with the labels that each got.

#619 update dependencies
  config.go
  go.mod
  go.sum
  main.go
  outputs/client.go
  outputs/policyreport.go
  outputs/rabbitmq.go
Labels: kind/cleanup, dco-signoff: yes, approved, lgtm, size/XXL, area/build, area/outputs

#628 fix panic in prometheus when hostname field is missing
  README.md
  handlers.go
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, area/outputs

#639 chore: remove refs to deprecated io/ioutil
  main.go
  outputs/client.go
  outputs/client_test.go
  outputs/spyderbat.go
Labels: dco-signoff: yes, approved, lgtm, needs-kind, size/M

#647 fix(loki): fix the deadlock in Loki integration
  outputs/loki.go
Labels: dco-signoff: yes, approved, lgtm, needs-kind, size/S

#649 add table of contents + fix missing link
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, size/M
