Repository falcosecurity/falcosidekick, pull requests merged in 2024-11, with the labels that each got.

#1043 [feature] add falco as source for datadog events
  outputs/datadog.go
  outputs/datadog_test.go
Labels: kind/feature, dco-signoff: yes, size/XS, approved, lgtm

#1051 allow to specify a list of alertmanager servers + fix attribute name ...
  config.go
  config_example.yaml
  docs/outputs/alertmanager.md
  handlers.go
  main.go
  outputs/alertmanager.go
  outputs/cloudevents.go
  stats_prometheus.go
  types/types.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/M, area/tests

#1062 update the CHANGELOG.md for the v2.30.0
  CHANGELOG.md
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/S, area/build, area/outputs
