Repository falcosecurity/falcosidekick, pull requests merged in 2024-07, with the labels that each got.

#937 specify goreleaser version
  .goreleaser.yml
Labels: kind/bug, dco-signoff: yes, size/XS, approved, lgtm, area/build

#938 updates for lint/goreleaser/dependabot
  .github/dependabot.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: kind/cleanup, dco-signoff: yes, approved, lgtm, size/S

#947 update go.mod to use toolchain 1.22.5
  go.mod
Labels: kind/cleanup, dco-signoff: yes, size/XS, approved, lgtm

#958 Update datadog.md to fix broken image
  docs/outputs/datadog.md
Labels: kind/documentation, dco-signoff: yes, size/XS, approved, lgtm, area/outputs
